version: '3.3'
services: 
  mongodb:
    container_name: cAndD_mongodb
    build:
        context: ./mongodb
        dockerfile: Dockerfile
    ports: 
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
