#keycloak:
#  realm: haushaltsapp
#  auth-server-url: http://localhost:8090/auth
#  ssl-required: external
#  resource: ad
#  use-resource-role-mappings: true
#  bearer-only: true
#  credentials:
#    secret: ${CLIENT_SECRETE}
#env:
#  keycloak:
#    host: ${KEYCLOAK_HOST:http://localhost:8090}
#    realm : ${KEYCLOAK_REALM:ABC-Company}

#keycloak:
#  realm: haushaltsapp
#  auth-server-url: http://localhost:8090/auth
#  resource: app-backend-springboot
#  bearer-only: true
#  ssl-required: external
#  principal-attribute: subject
#  use-resource-role-mappings: true
#
#  securityConstraints:
#    - authRoles: [user, admin]
#      securityCollections:
#        - name: API Private Data
#          patterns: ['/todos/search/my-todos/*']
#    - authRoles: [admin]
#      securityCollections:
#        - name: API
#          patterns: ['/todos/*']

keycloak:
  auth-server-url: http://localhost:8090/auth
  realm: haushaltsapp
  resource: ad
  public-client: true
  bearer-only: true